#cloud-config
users:
  - name: hebcal
    gecos: Hebcal
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-dss AAAAB3NzaC1kc3MAAAEBAKCDECinh9zUhHeKibZAumzTqk9MA0VVJJ4EH2Uf2wc1qXZlEA5d6k8LLc7FUZWQ8bn+4BjDEtXlzxAS/t3SmdFJCwaRhzu/5FDZi9usLCCbWsYgUos//uOD37Wpg0fkgIMVi/Jc0L8KceoHACuA9ORV9EIzmvvIFiz8ONKurRilGyL2QMncEN52MQgShv6nhAdFHk99/JAYY7SLhzy8UNBUQunpBJfNNGCHN+IPLMo7hiq5AfQxSHpo6dYeSLRJdWg76CMCf//VC7E/i+6ucHGsO/ZpZ3XVCP7dvt/U1j6qLcm0LWO0n3JrlrEOx9pwGgqyEopoeAaOrXgpydBxm/MAAAAVAIjvZ2FF09u4SQ+LuyQlIMfLB3HVAAABADR6tZndAMf/1p88jwc+Bo5wTglcPkktEXCxPMwrM5/WB6GCFsVGAZsn4/yOq8/Bijgy+RzKZT1is678Jk6Y+Ux1jTv8fjvKzSXn5G6/PT71ayElyKxo3WUTP5m0tnbwLXGBSJz1FfAGv7LHLC7+Crn+1Mlu0N4+JAoxd/C2xK/A1UdeeCwdfHOTuHB0wYEvf0vBSv+6qCv3aKC8cu6kstemijMCCXLPnK0uwls/1lgseeZCz2fOcW1N6kQgrSddHfyqQrQS1Zw22fRYepAYKPUmx3AcFJ6pWp3nZq7eboTRqzcJ8WL1LTrBnArZ/H7u974AuWE2u5hF50k38J8zvJEAAAEAZg9HmKsR/tEGah899pMSCpuTxrVcI3P969qbNq6i4na7S8UE2jd36Vs+bseibHlH+cTm9Fdtey990RuKklBoXlDovOKrmQ2dpzcIDUDyrAs/uRxVHqeZ8KKg9VDsf6xf0kHMX5sCFlge085o8c3AS+bu/pYLRlUpx8LGmshy9HNbHSoU4iAsB/EdRtSnor3vaZozHurPiVM7UwgW9w+C4aK5eQoHL45tTrDefDRCHn+b1w7ZTnEqM/vpHtpBvsN3FErnPVPmTuWl+EBNFRoNE5TzMcBJMa3p80t23VGaa+0mbNPE6VlIzbkXP1jZdw2sEpvE/UxdOnTnN9QAY8g9UA== mradwin@michael-radwins-computer.local
  - name: mradwin
    gecos: Michael J. Radwin
    groups: sudo
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-dss AAAAB3NzaC1kc3MAAAEBAKCDECinh9zUhHeKibZAumzTqk9MA0VVJJ4EH2Uf2wc1qXZlEA5d6k8LLc7FUZWQ8bn+4BjDEtXlzxAS/t3SmdFJCwaRhzu/5FDZi9usLCCbWsYgUos//uOD37Wpg0fkgIMVi/Jc0L8KceoHACuA9ORV9EIzmvvIFiz8ONKurRilGyL2QMncEN52MQgShv6nhAdFHk99/JAYY7SLhzy8UNBUQunpBJfNNGCHN+IPLMo7hiq5AfQxSHpo6dYeSLRJdWg76CMCf//VC7E/i+6ucHGsO/ZpZ3XVCP7dvt/U1j6qLcm0LWO0n3JrlrEOx9pwGgqyEopoeAaOrXgpydBxm/MAAAAVAIjvZ2FF09u4SQ+LuyQlIMfLB3HVAAABADR6tZndAMf/1p88jwc+Bo5wTglcPkktEXCxPMwrM5/WB6GCFsVGAZsn4/yOq8/Bijgy+RzKZT1is678Jk6Y+Ux1jTv8fjvKzSXn5G6/PT71ayElyKxo3WUTP5m0tnbwLXGBSJz1FfAGv7LHLC7+Crn+1Mlu0N4+JAoxd/C2xK/A1UdeeCwdfHOTuHB0wYEvf0vBSv+6qCv3aKC8cu6kstemijMCCXLPnK0uwls/1lgseeZCz2fOcW1N6kQgrSddHfyqQrQS1Zw22fRYepAYKPUmx3AcFJ6pWp3nZq7eboTRqzcJ8WL1LTrBnArZ/H7u974AuWE2u5hF50k38J8zvJEAAAEAZg9HmKsR/tEGah899pMSCpuTxrVcI3P969qbNq6i4na7S8UE2jd36Vs+bseibHlH+cTm9Fdtey990RuKklBoXlDovOKrmQ2dpzcIDUDyrAs/uRxVHqeZ8KKg9VDsf6xf0kHMX5sCFlge085o8c3AS+bu/pYLRlUpx8LGmshy9HNbHSoU4iAsB/EdRtSnor3vaZozHurPiVM7UwgW9w+C4aK5eQoHL45tTrDefDRCHn+b1w7ZTnEqM/vpHtpBvsN3FErnPVPmTuWl+EBNFRoNE5TzMcBJMa3p80t23VGaa+0mbNPE6VlIzbkXP1jZdw2sEpvE/UxdOnTnN9QAY8g9UA== mradwin@michael-radwins-computer.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCoHvNAA5UBj4DpCZsTtjjX82mM2eBECmc6wGXtZeaeqxyBdJBkkDfPmZwwL6OfCceoGHvU4zPEvonFFkjgDwRQYItVnYA4LolgbAjTVf0Bi+dv7Ny8B4fuMin0GvdrCs3BiX018Dw0za5UlopHESPHTKyAOAovR0tftQ+AzAFzae6ac/zZHK0odvoqWROlxSxOJZZl61EVM42ExYOSKm5tsc3g/ObW4wtaMOKUFHGFHfeeSRzYy1kacPVwIbEKTRCh8gLrL3yfOW/un6XF0U9eB+cqE0mVASWTOY59V7EWMJnUZaQcB8yZDeSF/iNEnB2e6ewUMo5X4nqYTaofTUjv mradwin@MTVL12027dd2a
  - name: nagios
    gecos: Nagios
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkIbumcez+ggabZq5wJwgA226Q09hG2AT45+epPdXL4KpEn46kb3ZF1Gk1QTUQhMUiDQaoHUGwUSAxGUcC/dOfDkBPHfpDLNZylvGzDMjLg8lvw1/IQC2XbCmDTqZ13Dqc2dnex9hN+N7NimnqaaGW0rvIDjlz27r0tr7N66oXTvPsWItahBQowSkr+agoCLeWxzjKUAabZJ38yp6TNFjU53WadiFGSF7gVjBhGId7F8ukSu2yYl/0i6isU3VK72q7AfKcp/n0dcm1t+BsQKJjH6AY1lmf5R6ZO2qAlRorzpYMzlK5A5VYcp4ILgKSTWKnFNHoP508/4UjD9Pt7uoL nagios@hebcalmonitor

debconf_selections: |     # Need to perserve newlines
    unattended-upgrades unattended-upgrades/enable_auto_updates boolean true
    postfix postfix/main_mailer_type select Satellite system
    postfix postfix/relayhost string email-smtp.us-east-1.amazonaws.com

package_upgrade: true

packages:
  - git
  - make
  - gcc
  - sqlite3
  - autoconf
  - automake
  - sysstat
  - netfilter-persistent
  - iptables-persistent
  - libsasl2-modules
  - postfix
  - bsd-mailx
  - fetchmail
  - procmail
  - rcs
  - mysql-client
  - apache2
  - apache2-dev
  - php7.4
  - php-mbstring
  - php-mysql
  - php-pear
  - php-sqlite3
  - php-json
  - php-curl
  - php-imagick
  - php-zip
  - libapache2-mod-php7.4
  - libcgi-pm-perl
  - libdate-calc-perl
  - libdatetime-perl
  - libpdf-api2-perl
  - libnet-smtp-ssl-perl
  - libmime-lite-perl
  - libxml-simple-perl
  - libconfig-tiny-perl
  - liblog-log4perl-perl
  - libdbd-sqlite3-perl
  - libdbd-mysql-perl
  - libhtml-calendarmonthsimple-perl
  - libjson-perl
  - libjson-xs-perl
  - libemail-valid-perl
  - libmail-deliverystatus-bounceparser-perl
  - libamazon-sqs-simple-perl
  - libmaxminddb-dev
  - monitoring-plugins-basic
  - python-magic
  - perlmagick
  - unzip
  - unattended-upgrades
  - awscli

write_files:
  - path: /etc/php/7.4/apache2/conf.d/50-hebcal.ini
    permissions: '0644'
    content: |
        ; configuration for php Hebcal
        ; priority=50
        date.timezone=America/New_York
        opcache.memory_consumption=128
        opcache.interned_strings_buffer=8
        opcache.max_accelerated_files=4000
        opcache.revalidate_freq=60
        opcache.fast_shutdown=1
        opcache.enable_cli=1
        opcache.save_comments=0
        opcache.enable_file_override=1
  - path: /etc/mailname
    permissions: '0644'
    content: |
      hebcal.com
  - path: /etc/default/sysstat
    permissions: '0644'
    content: |
      ENABLED="true"
  - path: /usr/local/etc/GeoIP.conf
    permissions: '0644'
    content: |
      # GeoIP.conf file for `geoipupdate` program, for versions >= 3.1.1.
      AccountID 122909
      LicenseKey YOUR_LICENSE_KEY_HERE
      EditionIDs GeoLite2-Country

runcmd:
  - service netfilter-persistent flush
  - iptables -F
  - iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  - iptables -A INPUT -p tcp --dport ssh -j ACCEPT
  - iptables -A INPUT -p tcp --dport http -j ACCEPT
  - iptables -A INPUT -p tcp --dport https -j ACCEPT
  - iptables -A INPUT -p icmp -j ACCEPT
  - iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT
  - iptables -A INPUT -j DROP
  - iptables -I INPUT 1 -i lo -j ACCEPT
  - service netfilter-persistent save
  - a2enmod rewrite
  - a2enmod headers
  - a2enmod expires
  - a2enmod cgi
  - a2enmod remoteip
  - a2dismod -f autoindex
  - a2dismod -f ssl
  - perl -pi -e 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf
  - perl -pi -e 's/StartServers\s+\d+/StartServers 30/' /etc/apache2/mods-available/mpm_prefork.conf
  - perl -pi -e 's/MinSpareServers\s+\d+/MinSpareServers 30/' /etc/apache2/mods-available/mpm_prefork.conf
  - perl -pi -e 's/MaxSpareServers\s+\d+/MaxSpareServers 30/' /etc/apache2/mods-available/mpm_prefork.conf
  - perl -pi -e 's/MaxRequestWorkers\s+\d+/MaxRequestWorkers 60/' /etc/apache2/mods-available/mpm_prefork.conf
  - pear channel-update pear.php.net
  - pear install --alldeps Mail
  - pear install --alldeps Net_SMTP
  - pear install --alldeps Auth_SASL
  - fallocate -l 2G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - swapon -s
  - free -m
  - echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
  - sysctl vm.swappiness=10
  - sysctl vm.vfs_cache_pressure=50
  - echo "vm.swappiness = 10" >> /etc/sysctl.conf
  - echo "vm.vfs_cache_pressure = 50" >> /etc/sysctl.conf
  - adduser mradwin hebcal
  - perl -pi -e 's/^.*PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl reload ssh.service
  - git clone https://github.com/maxmind/mod_maxminddb.git /tmp/mod_maxminddb
  - cd /tmp/mod_maxminddb && aclocal && autoconf && automake --foreign --add-missing && ./configure && make install
  - mkdir -p /usr/share/GeoIP
  - curl -o /tmp/GeoLite2-Country.tar.gz 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=j4Jxf3gL5qXqbcUA&suffix=tar.gz'
  - cd /tmp && tar xvfz GeoLite2-Country.tar.gz
  - rsync -av /tmp/GeoLite2-Country_*/GeoLite2-Country.mmdb /usr/share/GeoIP/GeoIP2-Country.mmdb
  - git clone https://github.com/hebcal/dotcom.git /tmp/dotcom
  - cp /tmp/dotcom/devops/etc/cron.d/hebcal /etc/cron.d/hebcal
  - cp /tmp/dotcom/devops/etc/postfix/main.cf /etc/postfix/main.cf
  - cp /tmp/dotcom/devops/etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf
  - systemctl restart apache2.service
  - rsync -a /tmp/dotcom/hebcal.com/ /var/www/
  - git clone https://github.com/hebcal/hebcal.git /tmp/hebcal-cli
  - rsync -av /tmp/hebcal-cli/ /var/hebcal/
  - cd /tmp/hebcal-cli && ./configure && make
  - rsync -av /tmp/hebcal-cli/hebcal /var/www/bin/
  - mkdir -p /home/hebcal/local/share/perl/site_perl
  - rsync -av /tmp/dotcom/local/share/perl/site_perl/ /home/hebcal/local/share/perl/site_perl/
  - rm -rf /tmp/dotcom/hebcal
  - ln -s /tmp/hebcal-cli /tmp/dotcom/hebcal
  - ln -s /tmp/hebcal-cli/hebcal /tmp/dotcom/hebcal.com/bin/hebcal
  - make -C /tmp/dotcom/hebcal.com/bin xml2perl
  - cd /home/hebcal/local
  - mkdir -p bin etc var/log
  - rsync -av /tmp/dotcom/local/bin/ /home/hebcal/local/bin/
  - rsync -av /tmp/dotcom/procmail/hebcron.procmailrc /home/hebcal/.procmailrc
  - rsync -av /tmp/dotcom/procmail/hebcron.fetchmailrc /home/hebcal/.fetchmailrc
  - chmod 0600 /home/hebcal/.fetchmailrc
  - mkdir -p /home/hebcal/mail
  - chown -R hebcal:hebcal /home/hebcal
  - rsync -av /tmp/dotcom/hebcal.com/pear/Hebcal/const.inc /var/www/pear/Hebcal/
  - curl -o /tmp/countryInfo.txt http://download.geonames.org/export/dump/countryInfo.txt
  - curl -o /tmp/admin1CodesASCII.txt http://download.geonames.org/export/dump/admin1CodesASCII.txt
  - curl -o /tmp/cities5000.zip http://download.geonames.org/export/dump/cities5000.zip
  - curl -o /tmp/IL.zip http://download.geonames.org/export/dump/IL.zip
  - cd /tmp && unzip cities5000.zip
  - cd /tmp && unzip IL.zip
  - /tmp/dotcom/local/bin/geonames_cities_sqlite.pl /var/www/hebcal/geonames.sqlite3 /tmp/countryInfo.txt /tmp/cities5000.txt /tmp/admin1CodesASCII.txt /tmp/IL.txt
  - mkdir -p /var/www/shabbat/browse
  - chown -R hebcal:hebcal /var/www
  - sudo -u hebcal make -C /var/www/bin converter
  - sudo -u hebcal make -C /var/www/bin holidays
  - sudo -u hebcal make -C /var/www/bin sedrot
  - sudo -u hebcal /var/www/bin/gen_current.pl
  - chown -R www-data:www-data /tmp/hebcal-cache
  - cd /var/www/holidays && sudo -u hebcal /var/www/bin/fetch_pdf.sh
  - sudo -u hebcal nice /var/www/bin/create_shabbat_browse.pl -v /var/www/shabbat/browse
