
(function(){var _Dom={get:function(el){if(typeof el=='string'){return document.getElementById(el);}else{return el;}}};var _Event={add:function(){if(typeof window.addEventListener!='undefined'){return function(el,type,fn){_Dom.get(el).addEventListener(type,fn,false);};}else if(typeof window.attachEvent!='undefined'){return function(el,type,fn){if(el==window&&type=='load'){var oldOnload=window.onload;if(typeof oldOnload!='function'){window.onload=fn;}else{window.onload=function(){if(oldOnload){oldOnload();}
fn();};}}else{var f=function(){fn.call(_Dom.get(el),window.event);};_Dom.get(el).attachEvent('on'+type,f);}};}}()};var _getFullYear=function(d){var yr=d.getYear();if(yr<1000)
yr+=1900;return yr;};var _numDaysIn=function(mo,yr){if(mo==4||mo==6||mo==9||mo==11)return 30;else if((mo==2)&&_leapYear(yr))return 29;else if(mo==2)return 28;else return 31;};var _leapYear=function(yr){if(((yr%4==0)&&yr%100!=0)||yr%400==0)return true;else return false;};var _prevMonth=function(mth){if(mth==1)return 12;else return(mth-1);};var _nextMonth=function(mth){if(mth==12)return 1;else return(mth+1);};var _prevYearMonth=function(yrmth){if((yrmth%100)==1)return((yrmth-100)+11);else return(yrmth-1);};var _nextYearMonth=function(yrmth){if((yrmth%100)==12)return((yrmth-11)+100);else return(yrmth+1);};JEC=function(container,options){var _container;_Event.add(window,'load',function(){_container=_Dom.get(container);});options=options||{};var _tableClass=options.tableClass||'JEC';var _specialDay=(options.specialDay===0?0:options.specialDay?options.specialDay:0);var _linkNewWindow=options.linkNewWindow===false?false:true;var _months=options.months||['January','February','March','April','May','June','July','August','September','October','November','December'];var _weekdays=options.weekdays||['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];var _today=new Date();var _firstMonth=options.firstMonth||_getFullYear(_today)*100+1;var _lastMonth=options.lastMonth||_firstMonth+11;var _events=[];var _buildDate=function(yr,mo,dy,dayofweek,currentyear,currentmonth,currentday){var elTd=document.createElement('td');var classes='';if(dayofweek==_specialDay)classes+=' daySpecial';if((yr==currentyear)&&(mo==currentmonth)&&(dy==currentday))classes+=' dayToday';var elDate=document.createElement('div');elDate.setAttribute('class','date');elDate.className='date';elDate.innerHTML=dy;elTd.appendChild(elDate);var ind=(((yr*100)+mo)*100)+dy;if(_events[ind]){classes+=' dayHasEvent';elTd.appendChild(_events[ind]);}
elTd.setAttribute('class',classes);elTd.className=classes;return elTd;};var _buildMonth=function(yearmonth){var curdy,curmo,curyr,yr,mo,dy,dayofweek,bgn,lastday;if(typeof yearmonth=='string')yearmonth=parseInt(yearmonth);mo=yearmonth%100;yr=(yearmonth-mo)/100;curdy=_today.getDate();curmo=_today.getMonth()+1;curyr=_getFullYear(_today);if(yearmonth<_firstMonth){mo=_firstMonth%100;yr=(_firstMonth-mo)/100;yearmonth=_firstMonth;}
if(yearmonth>_lastMonth){mo=_lastMonth%100;yr=(_lastMonth-mo)/100;yearmonth=_lastMonth;}
bgn=new Date(_months[mo-1]+' 1,'+yr);dayofweek=bgn.getDay();lastday=_numDaysIn(mo,yr);var elThead=document.createElement('thead');var elTr=document.createElement('tr');var elTh=document.createElement('th');elTh.setAttribute('colspan',7);elTh.setAttribute('colSpan',7);elTh.innerHTML=_months[mo-1]+'&nbsp;'+yr;elTr.appendChild(elTh);elThead.appendChild(elTr);var elTbody=document.createElement('tbody');elTr=document.createElement('tr');for(var i=0;i<7;i++){elTh=document.createElement('th');elTh.innerHTML=_weekdays[i];elTr.appendChild(elTh);}
elTbody.appendChild(elTr);elTr=document.createElement('tr');var elTd=document.createElement('td');dy=1;for(var i=1;i<=7;i++){if(i>dayofweek){elTd=_buildDate(yr,mo,dy,i,curyr,curmo,curdy);dy++;}else{elTd=document.createElement('td');elTd.setAttribute('class','dayBlank');elTd.className='dayBlank';}
elTr.appendChild(elTd);}
elTbody.appendChild(elTr);while(dy<=lastday){elTr=document.createElement('tr');for(var i=1;i<=7;i++){if(dy<=lastday){elTd=_buildDate(yr,mo,dy,i,curyr,curmo,curdy);dy++;}else{elTd=document.createElement('td');elTd.setAttribute('class','dayBlank');elTd.className='dayBlank';}
elTr.appendChild(elTd);}
elTbody.appendChild(elTr);}
var elTfoot=document.createElement('tfoot');elTr=document.createElement('tr');elTh=document.createElement('th');elTh.setAttribute('colspan',2);elTh.setAttribute('colSpan',2);if(yearmonth>_firstMonth){var elA=document.createElement('a');elA.setAttribute('href','javascript:;');_Event.add(elA,'click',function(){showCalendar(_prevYearMonth(yearmonth));});elA.innerHTML='&larr;&nbsp;'+_months[_prevMonth(mo)-1];elTh.appendChild(elA);}
elTr.appendChild(elTh);elTh=document.createElement('th');elTh.setAttribute('colspan',3);elTh.setAttribute('colSpan',3);var elSelect=document.createElement('select');elSelect.setAttribute('size',1);_Event.add(elSelect,'change',function(){showCalendar(this.options[this.selectedIndex].value);});for(var ym=_firstMonth;ym<=_lastMonth;ym=_nextYearMonth(ym)){var selMo=ym%100;var selYr=(ym-selMo)/100;var elOption=document.createElement('option');elOption.setAttribute('value',ym);if(ym==yearmonth)elOption.setAttribute('selected','selected');elOption.innerHTML=_months[selMo-1]+' '+selYr;elSelect.appendChild(elOption);}
elTh.appendChild(elSelect);elTr.appendChild(elTh);elTh=document.createElement('th');elTh.setAttribute('colspan',2);elTh.setAttribute('colSpan',2);if(yearmonth<_lastMonth){var elA=document.createElement('a');elA.setAttribute('href','javascript:;');_Event.add(elA,'click',function(){showCalendar(_nextYearMonth(yearmonth));});elA.innerHTML=_months[_nextMonth(mo)-1]+'&nbsp;&rarr;';elTh.appendChild(elA);}
elTr.appendChild(elTh);elTfoot.appendChild(elTr);var elTable=document.createElement('table');elTable.setAttribute('class',_tableClass);elTable.className=_tableClass;elTable.appendChild(elThead);elTable.appendChild(elTbody);elTable.appendChild(elTfoot);return elTable;};var _displayCalendar=function(elTable){if(_container.hasChildNodes()){while(_container.childNodes.length>=1){_container.removeChild(_container.firstChild);}}
_container.appendChild(elTable);};var defineEvent=function(eventDate,eventDescription,eventLink,image,width,height){var elEventBlock;if(_events[eventDate]){elEventBlock=_events[eventDate];elEventBlock.appendChild(document.createElement('br'));}else{elEventBlock=document.createElement('div');elEventBlock.setAttribute('class','events');elEventBlock.className='events';}
if(image&&image!=''){var elImg=document.createElement('img');elImg.setAttribute('src',image);if(width&&height){elImg.setAttribute('width',width);elImg.setAttribute('height',height);}
elEventBlock.appendChild(elImg);}
if(eventLink&&eventLink!=''){var elA=document.createElement('a');elA.setAttribute('href',eventLink);if(_linkNewWindow)
elA.setAttribute('target','_blank');elA.innerHTML=eventDescription;elEventBlock.appendChild(elA);}else{var elSpan=document.createElement('span');elSpan.innerHTML=eventDescription;elEventBlock.appendChild(elSpan);}
_events[eventDate]=elEventBlock;var tmp=Math.floor(eventDate/100);if(tmp<_firstMonth)_firstMonth=tmp;if(tmp>_lastMonth)_lastMonth=tmp;};var defineEvents=function(eventObjectArray){for(var i in eventObjectArray){var eventObject=eventObjectArray[i];var eventDate=eventObject.eventDate;var eventDescription=eventObject.eventDescription;var eventLink=eventObject.eventLink;var image=eventObject.image;var imageWidth=eventObject.imageWidth;var imageHeight=eventObject.imageHeight;defineEvent(eventDate,eventDescription,eventLink,image,imageWidth,imageHeight);}};var showCalendar=function(yearmonth){if(!yearmonth){var curmo=_today.getMonth()+1;var mo=curmo;var yr=_getFullYear(_today);yearmonth=(yr*100)+mo;}
var elTable=_buildMonth(yearmonth);if(_container){_displayCalendar(elTable);}else{_Event.add(window,'load',function(){_displayCalendar(elTable);});}};return{defineEvent:defineEvent,defineEvents:defineEvents,showCalendar:showCalendar};};})();